/** Stable, branchable classification for every error this library throws. */
export enum ErrorCode {
  VALIDATION = 'VALIDATION',
  NOT_FOUND = 'NOT_FOUND',
  CONDITION_CONFLICT = 'CONDITION_CONFLICT',
  RETRY_EXHAUSTED = 'RETRY_EXHAUSTED',
  BATCH_WRITE_INCOMPLETE = 'BATCH_WRITE_INCOMPLETE',
  COMPRESSION_LIMIT = 'COMPRESSION_LIMIT',
  S3_OFFLOAD_FAILED = 'S3_OFFLOAD_FAILED',
  S3_ORPHAN_CLEANUP_FAILED = 'S3_ORPHAN_CLEANUP_FAILED',
  ABORTED = 'ABORTED',
}
