/** Stable, branchable classification for every error this library throws. */
export enum ErrorCode {
  VALIDATION = 'VALIDATION',
  CONDITION_CONFLICT = 'CONDITION_CONFLICT',
  RETRY_EXHAUSTED = 'RETRY_EXHAUSTED',
  BATCH_WRITE_INCOMPLETE = 'BATCH_WRITE_INCOMPLETE',
  COMPRESSION_LIMIT = 'COMPRESSION_LIMIT',
  S3_OFFLOAD_FAILED = 'S3_OFFLOAD_FAILED',
  RESULT_TRUNCATED = 'RESULT_TRUNCATED',
  ABORTED = 'ABORTED',
  COMPENSATION_FAILED = 'COMPENSATION_FAILED',
}
